# Generated by Django 2.1.7 on 2019-02-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(default='', max_length=100, unique=True)),
                ('title', models.CharField(default='', max_length=1000)),
                ('summary', models.TextField()),
                ('author', models.CharField(default='', max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField()),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('link', models.CharField(default='', max_length=1000, unique=True)),
                ('logo_link', models.CharField(default='', max_length=1000)),
                ('last_active_on', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.FeedSource'),
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Feed'),
        ),
        migrations.AddField(
            model_name='bookmarked',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Feed'),
        ),
    ]
